//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
namespace i18n
{
	public class Message
	{
		private static Message instance;
		private Hashtable textTable;

		private Message () {
			textTable = readTexts ();
		}

		public static Message getInstance() {
			if (instance == null) {
				instance = new Message ();
			}
			return instance;
		}

		public string getText(string key) {
			string message = key;
			if (textTable.ContainsKey (key)) {
				message = (string)textTable [key];
			}
			return message;
		}

		public static string get(string msgKey) {
			return Message.getInstance ().getText (msgKey);
		}

		private Hashtable readTexts() {
			Hashtable texts = new Hashtable ();

			texts.Add ("Play", "Jogar");
			texts.Add ("Options", "Opcoes");

			return texts;
		}

	}
}

